version: '2'
 
services:
  redis:
    image: redis:latest
    container_name: redis_cv2
    command: -server -bootstrap
    ports:
      - "6379:6379"
    volumes:
      - /srv/docker/redis:/var/lib/redis
    command: ["redis-server", "--appendonly", "yes"]

  app1:
    
    image: p5imagertut:latest
    expose:
      - "8000"
    tty: true
    container_name: node1_cv2
    links:
      - redis:redis
    environment:
      REDIS_URL: redis
    volumes:
      - ./nodeapp:/usr/src/app
  app2:
    
    image: p5imagertut:latest
    expose:
      - "8000"
    tty: true
    container_name: node2_cv2
    links:
      - redis:redis
    environment:
      REDIS_URL: redis
    volumes:
      - ./nodeapp:/usr/src/app
  
  proxy:
    build:
      context:  ./loadbalancer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app1
      - app2
