version: '2'
 
services:
  redis:
    image: redis:latest
    container_name: redis_cv2
    command: -server -bootstrap
    ports:
      - "6379:6379"
    volumes:
      - /srv/docker/redis:/var/lib/redis
    command: ["redis-server", "--appendonly", "yes"]

  app1:
    build:
      context:  ./nodeapp
      dockerfile: Dockerfile
    
    image: nodeimagep4
    expose:
      - "8000"
    tty: true
    container_name: node1_c
    links:
      - redis:redis
    environment:
      REDIS_URL: redis
    volumes:
      - ./nodeapp:/usr/src/app
  app2:
    build:
      context:  ./nodeapp
      dockerfile: Dockerfile
    
    image: nodeimagep4
    expose:
      - "8000"
    tty: true
    container_name: node2_c
    links:
      - redis:redis
    environment:
      REDIS_URL: redis
    volumes:
      - ./nodeapp:/usr/src/app